; Generated by nes2gbc stateful superblock emitter
; A lives in host A, X in B, Y in C across safe trace edges; dirty canonical HRAM is materialized at barriers

SECTION "Generated NES reset entry", ROM0
nes_reset:
    ld a, [nes_reset_count]
    inc a
    ld [nes_reset_count], a
    ld hl, $8000
    jp nes_dispatch_hl

SECTION "NES block 8000", ROMX, BANK[40]
nes_8000:
IF DEF(NES2GBC_PROFILE_TRACE)
    ld hl, $8000
    call nes_profile_trace_pc
ENDC
    ldh a, [nes_host_vblank_pending]
    and a
    jr z, :+
    ld hl, $8000
    call nes_poll_nmi_hl
    and a
    jp nz, nes_nmi_entry
:
    ; $8000: $A9 Lda Immediate
    ld a, $00
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    ; $8002: $85 Sta ZeroPage
    ld [$C000], a
    ld d, a ; refresh DE cache NES ZP $00
    ; $8004: $E6 Inc ZeroPage
    ldh [nes_a], a ; superblock materialize A
    ld a, d ; DE cache NES ZP $00
    inc a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    ld [$C000], a
    ld d, a ; refresh DE cache NES ZP $00
    ; $8006: $A5 Lda ZeroPage
    ld a, d ; DE cache NES ZP $00
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    ; $8008: $C9 Cmp Immediate
    ldh [nes_a], a ; superblock materialize A
    ld e, $10
    ldh a, [nes_a]
    sub e ; superblock fast compare
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    ld a, $00
    jr c, :+
    inc a
:
    ldh [nes_c_shadow], a
    ; $800A: $D0 Bne Relative
    ldh a, [nes_z_shadow]
    and a
    jp nz, nes_8004 ; collapsed same-bank conditional target
    ; redundant unconditional target jump removed
:
    jp nes_800C

SECTION "NES block 8004", ROMX, BANK[40]
nes_8004:
IF DEF(NES2GBC_PROFILE_TRACE)
    ld hl, $8004
    call nes_profile_trace_pc
ENDC
    ldh a, [nes_host_vblank_pending]
    and a
    jr z, :+
    ld hl, $8004
    call nes_poll_nmi_hl
    and a
    jp nz, nes_nmi_entry
:
    ; $8004: $E6 Inc ZeroPage
    ld a, [$C000]
    ld e, a ; seed DE cache NES ZP $00
    inc a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    ld [$C000], a
    ld e, a ; refresh DE cache NES ZP $00
    ; $8006: $A5 Lda ZeroPage
    ld a, e ; DE cache NES ZP $00
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    ; $8008: $C9 Cmp Immediate
    ldh [nes_a], a ; superblock materialize A
    ld d, a ; refresh DE cache nes_a
    ld e, $10
    ld a, d ; DE cache nes_a
    sub e ; superblock fast compare
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    ld a, $00
    jr c, :+
    inc a
:
    ldh [nes_c_shadow], a
    ; $800A: $D0 Bne Relative
    ldh a, [nes_z_shadow]
    and a
    jp nz, nes_8004
    ; fused backward conditional branch
:
    jp nes_800C

SECTION "NES block 800C", ROMX, BANK[40]
nes_800C:
IF DEF(NES2GBC_PROFILE_TRACE)
    ld hl, $800C
    call nes_profile_trace_pc
ENDC
    ; $800C: $4C Jmp Absolute
    jp nes_8000

SECTION "NES block 8010", ROMX, BANK[40]
nes_8010:
IF DEF(NES2GBC_PROFILE_TRACE)
    ld hl, $8010
    call nes_profile_trace_pc
ENDC
    ; NMI-exclusive safe-point retained as analysis barrier
IF 0
    ; NMI-exclusive safe-point poll elided: nested NES NMI impossible
ENDC
    ; $8010: $40 Rti Implied
    call nes_rti_pop_hl
    jp nes_rti_fast_dispatch ; guarded exact RTI return

SECTION "NES block 8011", ROMX, BANK[40]
nes_8011:
IF DEF(NES2GBC_PROFILE_TRACE)
    ld hl, $8011
    call nes_profile_trace_pc
ENDC
    ldh a, [nes_host_vblank_pending]
    and a
    jr z, :+
    ld hl, $8011
    call nes_poll_nmi_hl
    and a
    jp nz, nes_nmi_entry
:
    ; $8011: $40 Rti Implied
    call nes_rti_pop_hl
    jp nes_rti_fast_dispatch ; guarded exact RTI return

SECTION "NES dispatch table 0", ROMX[$4000], BANK[32]
    db BANK(nes_8000), $00
    dw nes_8000
    ds 12, $00
    db BANK(nes_8004), $00
    dw nes_8004
    ds 28, $00
    db BANK(nes_800C), $00
    dw nes_800C
    ds 12, $00
    db BANK(nes_8010), $00
    dw nes_8010
    db BANK(nes_8011), $00
    dw nes_8011
    ds 16312, $00

SECTION "NES dispatch table 1", ROMX[$4000], BANK[33]
    ds 16384, $00

SECTION "NES dispatch table 2", ROMX[$4000], BANK[34]
    ds 16384, $00

SECTION "NES dispatch table 3", ROMX[$4000], BANK[35]
    ds 16384, $00

SECTION "NES dispatch table 4", ROMX[$4000], BANK[36]
    ds 16384, $00

SECTION "NES dispatch table 5", ROMX[$4000], BANK[37]
    ds 16384, $00

SECTION "NES dispatch table 6", ROMX[$4000], BANK[38]
    ds 16384, $00

SECTION "NES dispatch table 7", ROMX[$4000], BANK[39]
    ds 16384, $00


; Cartridge/runtime metadata
SECTION "Generated runtime metadata", ROM0
nes_generated_init:
    ld a, $00
    ld [nes_mapper], a
    ld a, $00
    ld [nes_mirroring], a
    ld a, $01
    ld [nes_prg_16k_mirror], a
    ld a, $00
    ld [nes_chr_bank_mask], a
    ld a, $04
    ld [nes_chr_gbc_bank_base], a
    xor a
    ld [nes_chr_bank], a
    call nes_cache_prg16_to_wram
    ret

nes_nmi_entry:
    ; fixed NMI vector: bypass dynamic PC dispatch
    ld a, BANK(nes_8010)
    ld hl, nes_8010
    jp nes_jump_known_hl_a_8bit ; 8-bit translated-code bank switch
nes_irq_entry:
    ld hl, $8011
    jp nes_dispatch_hl

SECTION "NES PRG data 0", ROMX[$4000], BANK[1]
    INCBIN "generated.prg.bin", 0, $4000

SECTION "NES CHR data 0", ROMX[$4000], BANK[3]
    INCBIN "generated.chr.bin", $0000, $2000

SECTION "GBC converted CHR 0", ROMX[$4000], BANK[4]
    INCBIN "generated.chr.gbc.bin", $0000, $2000

; PocketNES-derived initial follow-camera hint
SECTION "Generated follow-camera metadata", ROM0
nes_generated_follow_init:
    ret

SECTION "Guarded RTI return fast dispatch", ROM0
nes_rti_fast_dispatch:
    ; HL is the exact PC popped by nes_rti_pop_hl.
    ld a, h
    cp $80
    jr nz, .next_hi_0
    ld a, l
    cp $04
    jr nz, .next_0_0
    ld a, BANK(nes_8004)
    ld hl, nes_8004
    jp nes_jump_known_hl_a_8bit ; 8-bit translated-code bank switch
.next_0_0:
    ld a, l
    cp $00
    jr nz, .next_0_1
    ld a, BANK(nes_8000)
    ld hl, nes_8000
    jp nes_jump_known_hl_a_8bit ; 8-bit translated-code bank switch
.next_0_1:
    ld a, l
    cp $11
    jr nz, .next_0_2
    ld a, BANK(nes_8011)
    ld hl, nes_8011
    jp nes_jump_known_hl_a_8bit ; 8-bit translated-code bank switch
.next_0_2:
.next_hi_0:
    ; Uncommon poll point, IRQ/BRK RTI, or modified stacked PC.
    jp nes_dispatch_hl

SECTION "Fast 8-bit translated bank switch", ROM0
nes_jump_known_hl_a_8bit:
    ; A = translated code bank (<256), HL = linked ROMX target.
    ; MBC5 bank bit 8 is already zero from the initial dispatcher.
    ld [nes_current_code_bank], a
    ld [$2000], a
    xor a ; preserve host-flag normalization of the original helper
    jp hl
