; Generated by tools/gen_ram_interp.py -- do not edit by hand.
; 6502 interpreter for code executing from RAM ($0000-$1FFF, $6000-$7FFF).

SECTION "NES RAM interpreter state", WRAM0
nes_ipc_lo: ds 1 ; interpreted 6502 PC
nes_ipc_hi: ds 1
nes_iea_lo: ds 1 ; effective address of the current instruction
nes_iea_hi: ds 1

SECTION "NES RAM interpreter entry", ROM0
; Input HL = NES PC below $8000. Enter the banked interpreter with the
; helper bank recorded as the current code bank, so every bus/CHR helper
; that temporarily switches ROMX banks returns to the interpreter.
nes_interp_enter:
    ld a, $FF
    ld [nes_current_code_bank], a
    ld [$2000], a
    xor a
    ld [$3000], a
    jp nes_interp_run

SECTION "NES RAM interpreter", ROMX, BANK[255]
nes_interp_run:
    ld a, l
    ld [nes_ipc_lo], a
    ld a, h
    ld [nes_ipc_hi], a
nes_interp_next:
    ld a, [nes_ipc_hi]
    cp $80
    jr c, .fetch
    ; Back in PRG ROM: continue in translated code.
    ld h, a
    ld a, [nes_ipc_lo]
    ld l, a
    jp nes_dispatch_hl
.fetch:
    call nes_interp_fetch
    ld l, a
    ld h, 0
    add hl, hl
    ld de, nes_interp_table
    add hl, de
    ld a, [hli]
    ld h, [hl]
    ld l, a
    jp hl

; A = byte at PC, PC += 1. Clobbers HL (and whatever nes_cpu_read clobbers).
nes_interp_fetch:
    ld hl, nes_ipc_lo
    ld a, [hli]
    ld h, [hl]
    ld l, a
    inc hl
    ld a, l
    ld [nes_ipc_lo], a
    ld a, h
    ld [nes_ipc_hi], a
    dec hl
    ; fall through
; A = NES bus byte at HL.
nes_interp_read_hl:
    ld a, h
    cp $20
    jp nc, nes_cpu_read
    and $07
    or $C0
    ld h, a
    ld a, [hl]
    ret

; Write A to NES bus address HL.
nes_interp_write_hl:
    ld e, a
    ld a, h
    cp $20
    jr nc, .bus
    and $07
    or $C0
    ld h, a
    ld [hl], e
    ret
.bus:
    ld a, e
    jp nes_cpu_write

; HL = 16-bit operand at PC, PC += 2.
nes_interp_fetch16:
    call nes_interp_fetch
    push af
    call nes_interp_fetch
    ld h, a
    pop af
    ld l, a
    ret

; Effective-address calculators: leave EA in nes_iea and HL.
nes_interp_ea_store:
    ld a, l
    ld [nes_iea_lo], a
    ld a, h
    ld [nes_iea_hi], a
    ret
nes_interp_ea_zp:
    call nes_interp_fetch
    ld l, a
    ld h, 0
    jr nes_interp_ea_store
nes_interp_ea_zpx:
    call nes_interp_fetch
    ld l, a
    ldh a, [nes_x]
    add l
    ld l, a
    ld h, 0
    jr nes_interp_ea_store
nes_interp_ea_zpy:
    call nes_interp_fetch
    ld l, a
    ldh a, [nes_y]
    add l
    ld l, a
    ld h, 0
    jr nes_interp_ea_store
nes_interp_ea_abs:
    call nes_interp_fetch16
    jr nes_interp_ea_store
nes_interp_ea_abx:
    call nes_interp_fetch16
    ldh a, [nes_x]
    jr nes_interp_ea_add_a
nes_interp_ea_aby:
    call nes_interp_fetch16
    ldh a, [nes_y]
nes_interp_ea_add_a:
    add l
    ld l, a
    jr nc, nes_interp_ea_store
    inc h
    jr nes_interp_ea_store
; Pointer HL (zero page) -> 16-bit little-endian value with zero-page wrap.
nes_interp_zp_ptr:
    ld h, $C0
    ld a, [hl]
    inc l
    ld h, [hl]
    ld l, a
    ld a, h
    ld h, a
    ret
nes_interp_ea_izx:
    call nes_interp_fetch
    ld l, a
    ldh a, [nes_x]
    add l
    ld l, a
    call nes_interp_zp_ptr
    jr nes_interp_ea_store
nes_interp_ea_izy:
    call nes_interp_fetch
    ld l, a
    call nes_interp_zp_ptr
    ldh a, [nes_y]
    jr nes_interp_ea_add_a

; Load the current operand value into A (immediate or via EA).
nes_interp_load_ea:
    ld a, [nes_iea_lo]
    ld l, a
    ld a, [nes_iea_hi]
    ld h, a
    jp nes_interp_read_hl
nes_interp_store_ea:
    push af
    ld a, [nes_iea_lo]
    ld l, a
    ld a, [nes_iea_hi]
    ld h, a
    pop af
    jp nes_interp_write_hl

; Taken control transfer to HL: poll for a pending NMI exactly like a
; translated loop head, then continue at HL.
nes_interp_goto_hl:
    ld a, l
    ld [nes_ipc_lo], a
    ld a, h
    ld [nes_ipc_hi], a
    ldh a, [nes_host_vblank_pending]
    and a
    jp z, nes_interp_next
    call nes_poll_nmi_hl
    and a
    jp nz, nes_nmi_entry
    jp nes_interp_next

nes_interp_illegal:
    ld a, [nes_ipc_lo]
    dec a
    ldh [nes_fault_pc_lo], a
    ld a, [nes_ipc_hi]
    ldh [nes_fault_pc_hi], a
    jp nes_unimplemented

nes_interp_op_00: ; BRK imp
    ld a, [nes_ipc_lo]
    ld l, a
    ld a, [nes_ipc_hi]
    ld h, a
    inc hl
    call nes_brk_hl
    jp nes_irq_entry

nes_interp_op_01: ; ORA izx
    call nes_interp_ea_izx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    or e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_05: ; ORA zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    or e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_06: ; ASL zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    call nes_asl_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_08: ; PHP imp
    call nes_materialize_p
    or $30
    call nes_stack_push_a
    jp nes_interp_next

nes_interp_op_09: ; ORA imm
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_a]
    or e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_0A: ; ASL acc
    ldh a, [nes_a]
    call nes_asl_a
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_0D: ; ORA abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    or e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_0E: ; ASL abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    call nes_asl_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_10: ; BPL rel
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_n_shadow]
    bit 7, a
    jr nz, .not_taken
    ld a, [nes_ipc_lo]
    ld l, a
    ld a, [nes_ipc_hi]
    ld h, a
    ld a, e
    ld d, $00
    bit 7, a
    jr z, :+
    dec d
:
    add hl, de
    jp nes_interp_goto_hl
.not_taken:
    jp nes_interp_next

nes_interp_op_11: ; ORA izy
    call nes_interp_ea_izy
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    or e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_15: ; ORA zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    or e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_16: ; ASL zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    call nes_asl_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_18: ; CLC imp
    xor a
    ldh [nes_c_shadow], a
    jp nes_interp_next

nes_interp_op_19: ; ORA aby
    call nes_interp_ea_aby
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    or e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_1D: ; ORA abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    or e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_1E: ; ASL abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    call nes_asl_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_20: ; JSR abs
    call nes_interp_fetch16
    push hl
    ld a, [nes_ipc_lo]
    ld l, a
    ld a, [nes_ipc_hi]
    ld h, a
    dec hl
    call nes_stack_push_return_hl
    pop hl
    jp nes_interp_goto_hl

nes_interp_op_21: ; AND izx
    call nes_interp_ea_izx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    and e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_24: ; BIT zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_bit_a_e
    jp nes_interp_next

nes_interp_op_25: ; AND zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    and e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_26: ; ROL zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    call nes_rol_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_28: ; PLP imp
    call nes_stack_pop_a
    call nes_set_p_from_a
    jp nes_interp_next

nes_interp_op_29: ; AND imm
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_a]
    and e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_2A: ; ROL acc
    ldh a, [nes_a]
    call nes_rol_a
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_2C: ; BIT abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_bit_a_e
    jp nes_interp_next

nes_interp_op_2D: ; AND abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    and e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_2E: ; ROL abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    call nes_rol_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_30: ; BMI rel
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_n_shadow]
    bit 7, a
    jr z, .not_taken
    ld a, [nes_ipc_lo]
    ld l, a
    ld a, [nes_ipc_hi]
    ld h, a
    ld a, e
    ld d, $00
    bit 7, a
    jr z, :+
    dec d
:
    add hl, de
    jp nes_interp_goto_hl
.not_taken:
    jp nes_interp_next

nes_interp_op_31: ; AND izy
    call nes_interp_ea_izy
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    and e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_35: ; AND zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    and e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_36: ; ROL zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    call nes_rol_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_38: ; SEC imp
    ld a, $01
    ldh [nes_c_shadow], a
    jp nes_interp_next

nes_interp_op_39: ; AND aby
    call nes_interp_ea_aby
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    and e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_3D: ; AND abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    and e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_3E: ; ROL abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    call nes_rol_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_40: ; RTI imp
    call nes_rti_pop_hl
    jp nes_interp_goto_hl

nes_interp_op_41: ; EOR izx
    call nes_interp_ea_izx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    xor e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_45: ; EOR zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    xor e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_46: ; LSR zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    call nes_lsr_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_48: ; PHA imp
    ldh a, [nes_a]
    call nes_stack_push_a
    jp nes_interp_next

nes_interp_op_49: ; EOR imm
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_a]
    xor e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_4A: ; LSR acc
    ldh a, [nes_a]
    call nes_lsr_a
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_4C: ; JMP abs
    call nes_interp_fetch16
    jp nes_interp_goto_hl

nes_interp_op_4D: ; EOR abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    xor e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_4E: ; LSR abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    call nes_lsr_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_50: ; BVC rel
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_p]
    and $40
    jr nz, .not_taken
    ld a, [nes_ipc_lo]
    ld l, a
    ld a, [nes_ipc_hi]
    ld h, a
    ld a, e
    ld d, $00
    bit 7, a
    jr z, :+
    dec d
:
    add hl, de
    jp nes_interp_goto_hl
.not_taken:
    jp nes_interp_next

nes_interp_op_51: ; EOR izy
    call nes_interp_ea_izy
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    xor e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_55: ; EOR zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    xor e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_56: ; LSR zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    call nes_lsr_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_58: ; CLI imp
    ldh a, [nes_p]
    and $FB
    ldh [nes_p], a
    jp nes_interp_next

nes_interp_op_59: ; EOR aby
    call nes_interp_ea_aby
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    xor e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_5D: ; EOR abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    xor e
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_5E: ; LSR abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    call nes_lsr_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_60: ; RTS imp
    call nes_stack_pop_return_hl
    inc hl
    jp nes_interp_goto_hl

nes_interp_op_61: ; ADC izx
    call nes_interp_ea_izx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_adc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_65: ; ADC zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_adc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_66: ; ROR zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    call nes_ror_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_68: ; PLA imp
    call nes_stack_pop_a
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_69: ; ADC imm
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_a]
    call nes_adc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_6A: ; ROR acc
    ldh a, [nes_a]
    call nes_ror_a
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_6C: ; JMP ind
    call nes_interp_fetch16
    call nes_jmp_indirect_hl
    jp nes_interp_goto_hl

nes_interp_op_6D: ; ADC abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_adc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_6E: ; ROR abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    call nes_ror_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_70: ; BVS rel
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_p]
    and $40
    jr z, .not_taken
    ld a, [nes_ipc_lo]
    ld l, a
    ld a, [nes_ipc_hi]
    ld h, a
    ld a, e
    ld d, $00
    bit 7, a
    jr z, :+
    dec d
:
    add hl, de
    jp nes_interp_goto_hl
.not_taken:
    jp nes_interp_next

nes_interp_op_71: ; ADC izy
    call nes_interp_ea_izy
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_adc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_75: ; ADC zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_adc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_76: ; ROR zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    call nes_ror_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_78: ; SEI imp
    ldh a, [nes_p]
    or $04
    ldh [nes_p], a
    jp nes_interp_next

nes_interp_op_79: ; ADC aby
    call nes_interp_ea_aby
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_adc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_7D: ; ADC abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_adc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_7E: ; ROR abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    call nes_ror_a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_81: ; STA izx
    call nes_interp_ea_izx
    ldh a, [nes_a]
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_84: ; STY zp
    call nes_interp_ea_zp
    ldh a, [nes_y]
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_85: ; STA zp
    call nes_interp_ea_zp
    ldh a, [nes_a]
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_86: ; STX zp
    call nes_interp_ea_zp
    ldh a, [nes_x]
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_88: ; DEY imp
    ldh a, [nes_y]
    dec a
    ldh [nes_y], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_8A: ; TXA imp
    ldh a, [nes_x]
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_8C: ; STY abs
    call nes_interp_ea_abs
    ldh a, [nes_y]
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_8D: ; STA abs
    call nes_interp_ea_abs
    ldh a, [nes_a]
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_8E: ; STX abs
    call nes_interp_ea_abs
    ldh a, [nes_x]
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_90: ; BCC rel
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_c_shadow]
    and a
    jr nz, .not_taken
    ld a, [nes_ipc_lo]
    ld l, a
    ld a, [nes_ipc_hi]
    ld h, a
    ld a, e
    ld d, $00
    bit 7, a
    jr z, :+
    dec d
:
    add hl, de
    jp nes_interp_goto_hl
.not_taken:
    jp nes_interp_next

nes_interp_op_91: ; STA izy
    call nes_interp_ea_izy
    ldh a, [nes_a]
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_94: ; STY zpx
    call nes_interp_ea_zpx
    ldh a, [nes_y]
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_95: ; STA zpx
    call nes_interp_ea_zpx
    ldh a, [nes_a]
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_96: ; STX zpy
    call nes_interp_ea_zpy
    ldh a, [nes_x]
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_98: ; TYA imp
    ldh a, [nes_y]
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_99: ; STA aby
    call nes_interp_ea_aby
    ldh a, [nes_a]
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_9A: ; TXS imp
    ldh a, [nes_x]
    ldh [nes_sp], a
    jp nes_interp_next

nes_interp_op_9D: ; STA abx
    call nes_interp_ea_abx
    ldh a, [nes_a]
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_A0: ; LDY imm
    call nes_interp_fetch
    ldh [nes_y], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_A1: ; LDA izx
    call nes_interp_ea_izx
    call nes_interp_load_ea
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_A2: ; LDX imm
    call nes_interp_fetch
    ldh [nes_x], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_A4: ; LDY zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    ldh [nes_y], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_A5: ; LDA zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_A6: ; LDX zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    ldh [nes_x], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_A8: ; TAY imp
    ldh a, [nes_a]
    ldh [nes_y], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_A9: ; LDA imm
    call nes_interp_fetch
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_AA: ; TAX imp
    ldh a, [nes_a]
    ldh [nes_x], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_AC: ; LDY abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    ldh [nes_y], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_AD: ; LDA abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_AE: ; LDX abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    ldh [nes_x], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_B0: ; BCS rel
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_c_shadow]
    and a
    jr z, .not_taken
    ld a, [nes_ipc_lo]
    ld l, a
    ld a, [nes_ipc_hi]
    ld h, a
    ld a, e
    ld d, $00
    bit 7, a
    jr z, :+
    dec d
:
    add hl, de
    jp nes_interp_goto_hl
.not_taken:
    jp nes_interp_next

nes_interp_op_B1: ; LDA izy
    call nes_interp_ea_izy
    call nes_interp_load_ea
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_B4: ; LDY zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    ldh [nes_y], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_B5: ; LDA zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_B6: ; LDX zpy
    call nes_interp_ea_zpy
    call nes_interp_load_ea
    ldh [nes_x], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_B8: ; CLV imp
    ldh a, [nes_p]
    and $BF
    ldh [nes_p], a
    jp nes_interp_next

nes_interp_op_B9: ; LDA aby
    call nes_interp_ea_aby
    call nes_interp_load_ea
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_BA: ; TSX imp
    ldh a, [nes_sp]
    ldh [nes_x], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_BC: ; LDY abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    ldh [nes_y], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_BD: ; LDA abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    ldh [nes_a], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_BE: ; LDX aby
    call nes_interp_ea_aby
    call nes_interp_load_ea
    ldh [nes_x], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_C0: ; CPY imm
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_y]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_C1: ; CMP izx
    call nes_interp_ea_izx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_C4: ; CPY zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_y]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_C5: ; CMP zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_C6: ; DEC zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    dec a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_C8: ; INY imp
    ldh a, [nes_y]
    inc a
    ldh [nes_y], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_C9: ; CMP imm
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_a]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_CA: ; DEX imp
    ldh a, [nes_x]
    dec a
    ldh [nes_x], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_CC: ; CPY abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_y]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_CD: ; CMP abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_CE: ; DEC abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    dec a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_D0: ; BNE rel
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_z_shadow]
    and a
    jr z, .not_taken
    ld a, [nes_ipc_lo]
    ld l, a
    ld a, [nes_ipc_hi]
    ld h, a
    ld a, e
    ld d, $00
    bit 7, a
    jr z, :+
    dec d
:
    add hl, de
    jp nes_interp_goto_hl
.not_taken:
    jp nes_interp_next

nes_interp_op_D1: ; CMP izy
    call nes_interp_ea_izy
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_D5: ; CMP zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_D6: ; DEC zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    dec a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_D8: ; CLD imp
    ldh a, [nes_p]
    and $F7
    ldh [nes_p], a
    jp nes_interp_next

nes_interp_op_D9: ; CMP aby
    call nes_interp_ea_aby
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_DD: ; CMP abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_DE: ; DEC abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    dec a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_E0: ; CPX imm
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_x]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_E1: ; SBC izx
    call nes_interp_ea_izx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_sbc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_E4: ; CPX zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_x]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_E5: ; SBC zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_sbc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_E6: ; INC zp
    call nes_interp_ea_zp
    call nes_interp_load_ea
    inc a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_E8: ; INX imp
    ldh a, [nes_x]
    inc a
    ldh [nes_x], a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    jp nes_interp_next

nes_interp_op_E9: ; SBC imm
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_a]
    call nes_sbc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_EA: ; NOP imp
    jp nes_interp_next

nes_interp_op_EC: ; CPX abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_x]
    call nes_compare_a_e
    jp nes_interp_next

nes_interp_op_ED: ; SBC abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_sbc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_EE: ; INC abs
    call nes_interp_ea_abs
    call nes_interp_load_ea
    inc a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_F0: ; BEQ rel
    call nes_interp_fetch
    ld e, a
    ldh a, [nes_z_shadow]
    and a
    jr nz, .not_taken
    ld a, [nes_ipc_lo]
    ld l, a
    ld a, [nes_ipc_hi]
    ld h, a
    ld a, e
    ld d, $00
    bit 7, a
    jr z, :+
    dec d
:
    add hl, de
    jp nes_interp_goto_hl
.not_taken:
    jp nes_interp_next

nes_interp_op_F1: ; SBC izy
    call nes_interp_ea_izy
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_sbc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_F5: ; SBC zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_sbc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_F6: ; INC zpx
    call nes_interp_ea_zpx
    call nes_interp_load_ea
    inc a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    call nes_interp_store_ea
    jp nes_interp_next

nes_interp_op_F8: ; SED imp
    ldh a, [nes_p]
    or $08
    ldh [nes_p], a
    jp nes_interp_next

nes_interp_op_F9: ; SBC aby
    call nes_interp_ea_aby
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_sbc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_FD: ; SBC abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    ld e, a
    ldh a, [nes_a]
    call nes_sbc_a_e
    ldh [nes_a], a
    jp nes_interp_next

nes_interp_op_FE: ; INC abx
    call nes_interp_ea_abx
    call nes_interp_load_ea
    inc a
    ldh [nes_z_shadow], a
    ldh [nes_n_shadow], a
    call nes_interp_store_ea
    jp nes_interp_next

SECTION "NES RAM interpreter table", ROMX, BANK[255]
nes_interp_table:
    dw nes_interp_op_00
    dw nes_interp_op_01
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_05
    dw nes_interp_op_06
    dw nes_interp_illegal
    dw nes_interp_op_08
    dw nes_interp_op_09
    dw nes_interp_op_0A
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_0D
    dw nes_interp_op_0E
    dw nes_interp_illegal
    dw nes_interp_op_10
    dw nes_interp_op_11
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_15
    dw nes_interp_op_16
    dw nes_interp_illegal
    dw nes_interp_op_18
    dw nes_interp_op_19
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_1D
    dw nes_interp_op_1E
    dw nes_interp_illegal
    dw nes_interp_op_20
    dw nes_interp_op_21
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_24
    dw nes_interp_op_25
    dw nes_interp_op_26
    dw nes_interp_illegal
    dw nes_interp_op_28
    dw nes_interp_op_29
    dw nes_interp_op_2A
    dw nes_interp_illegal
    dw nes_interp_op_2C
    dw nes_interp_op_2D
    dw nes_interp_op_2E
    dw nes_interp_illegal
    dw nes_interp_op_30
    dw nes_interp_op_31
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_35
    dw nes_interp_op_36
    dw nes_interp_illegal
    dw nes_interp_op_38
    dw nes_interp_op_39
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_3D
    dw nes_interp_op_3E
    dw nes_interp_illegal
    dw nes_interp_op_40
    dw nes_interp_op_41
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_45
    dw nes_interp_op_46
    dw nes_interp_illegal
    dw nes_interp_op_48
    dw nes_interp_op_49
    dw nes_interp_op_4A
    dw nes_interp_illegal
    dw nes_interp_op_4C
    dw nes_interp_op_4D
    dw nes_interp_op_4E
    dw nes_interp_illegal
    dw nes_interp_op_50
    dw nes_interp_op_51
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_55
    dw nes_interp_op_56
    dw nes_interp_illegal
    dw nes_interp_op_58
    dw nes_interp_op_59
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_5D
    dw nes_interp_op_5E
    dw nes_interp_illegal
    dw nes_interp_op_60
    dw nes_interp_op_61
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_65
    dw nes_interp_op_66
    dw nes_interp_illegal
    dw nes_interp_op_68
    dw nes_interp_op_69
    dw nes_interp_op_6A
    dw nes_interp_illegal
    dw nes_interp_op_6C
    dw nes_interp_op_6D
    dw nes_interp_op_6E
    dw nes_interp_illegal
    dw nes_interp_op_70
    dw nes_interp_op_71
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_75
    dw nes_interp_op_76
    dw nes_interp_illegal
    dw nes_interp_op_78
    dw nes_interp_op_79
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_7D
    dw nes_interp_op_7E
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_81
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_84
    dw nes_interp_op_85
    dw nes_interp_op_86
    dw nes_interp_illegal
    dw nes_interp_op_88
    dw nes_interp_illegal
    dw nes_interp_op_8A
    dw nes_interp_illegal
    dw nes_interp_op_8C
    dw nes_interp_op_8D
    dw nes_interp_op_8E
    dw nes_interp_illegal
    dw nes_interp_op_90
    dw nes_interp_op_91
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_94
    dw nes_interp_op_95
    dw nes_interp_op_96
    dw nes_interp_illegal
    dw nes_interp_op_98
    dw nes_interp_op_99
    dw nes_interp_op_9A
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_9D
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_A0
    dw nes_interp_op_A1
    dw nes_interp_op_A2
    dw nes_interp_illegal
    dw nes_interp_op_A4
    dw nes_interp_op_A5
    dw nes_interp_op_A6
    dw nes_interp_illegal
    dw nes_interp_op_A8
    dw nes_interp_op_A9
    dw nes_interp_op_AA
    dw nes_interp_illegal
    dw nes_interp_op_AC
    dw nes_interp_op_AD
    dw nes_interp_op_AE
    dw nes_interp_illegal
    dw nes_interp_op_B0
    dw nes_interp_op_B1
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_B4
    dw nes_interp_op_B5
    dw nes_interp_op_B6
    dw nes_interp_illegal
    dw nes_interp_op_B8
    dw nes_interp_op_B9
    dw nes_interp_op_BA
    dw nes_interp_illegal
    dw nes_interp_op_BC
    dw nes_interp_op_BD
    dw nes_interp_op_BE
    dw nes_interp_illegal
    dw nes_interp_op_C0
    dw nes_interp_op_C1
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_C4
    dw nes_interp_op_C5
    dw nes_interp_op_C6
    dw nes_interp_illegal
    dw nes_interp_op_C8
    dw nes_interp_op_C9
    dw nes_interp_op_CA
    dw nes_interp_illegal
    dw nes_interp_op_CC
    dw nes_interp_op_CD
    dw nes_interp_op_CE
    dw nes_interp_illegal
    dw nes_interp_op_D0
    dw nes_interp_op_D1
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_D5
    dw nes_interp_op_D6
    dw nes_interp_illegal
    dw nes_interp_op_D8
    dw nes_interp_op_D9
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_DD
    dw nes_interp_op_DE
    dw nes_interp_illegal
    dw nes_interp_op_E0
    dw nes_interp_op_E1
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_E4
    dw nes_interp_op_E5
    dw nes_interp_op_E6
    dw nes_interp_illegal
    dw nes_interp_op_E8
    dw nes_interp_op_E9
    dw nes_interp_op_EA
    dw nes_interp_illegal
    dw nes_interp_op_EC
    dw nes_interp_op_ED
    dw nes_interp_op_EE
    dw nes_interp_illegal
    dw nes_interp_op_F0
    dw nes_interp_op_F1
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_F5
    dw nes_interp_op_F6
    dw nes_interp_illegal
    dw nes_interp_op_F8
    dw nes_interp_op_F9
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_illegal
    dw nes_interp_op_FD
    dw nes_interp_op_FE
    dw nes_interp_illegal
