#!/usr/bin/env python3
"""Turn static mapper-1/2 block exits into direct known-bank transfers.

The banked emitter ends every block with `ld hl, $T / jp nes_dispatch_hl`,
paying a dispatch-cache probe (and, on a miss, a table-bank lookup) for
every statically known edge. The dispatch table always maps T to the label
nes_T (a fixed-bank block or a bank-aware stub), so jumping to nes_T is
exactly what dispatch would do. When the source is a $8000-$BFFF variant of
bank NN that cannot write a mapper register (`; m2-bank-stable`), the mapped
bank is still NN at its exit and a $8000-$BFFF target may enter
nes_m2_bNN_T directly, skipping the stub's bank compare as well.

Rewrites to `ld a, BANK(L) / ld hl, L / jp nes_jump_known_hl_a`; the later
fast_code_bank_switch and repack passes shrink these (direct `jp` within a
bank). Targets without a translation keep the dispatcher (interpreter
fallback). Files not produced by the banked emitter are left untouched.
"""
from __future__ import annotations
import re, sys
from pathlib import Path

MARK = "; Generated by nes2gbc mapper-2 banked emitter"
SEC_RE = re.compile(r'^\s*SECTION\s+"NES (?:block ([0-9A-F]{4})|mapper2 b([0-9A-F]{2}) block ([0-9A-F]{4})|overlay block ([0-9A-F]{4}))"')
ANY_SEC = re.compile(r"^\s*SECTION\b")
LABEL_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):{1,2}$")
LD_RE = re.compile(r"^ld hl, \$([0-9A-F]{4})$")


def code(l: str) -> str:
    return l.split(";", 1)[0].strip()


def main(path: str) -> None:
    p = Path(path)
    text = p.read_text()
    if MARK not in text:
        print("banked-direct: not a banked-mapper build, skipped")
        return
    lines = text.splitlines(keepends=True)
    labels = set()
    for l in lines:
        m = LABEL_RE.match(code(l))
        if m:
            labels.add(m.group(1))
    out = list(lines)
    view = None      # bank NN of the current $8000-$BFFF variant section
    stable = False
    pure = False     # current overlay block cannot store into PRG RAM
    in_code = False
    n_fixed = n_stub = n_variant = n_overlay = kept = 0
    for i, l in enumerate(lines):
        if ANY_SEC.match(l):
            m = SEC_RE.match(l)
            in_code = bool(m)
            view = m.group(2) if m and m.group(2) else None
            stable = False
            pure = False
            continue
        if not in_code:
            continue
        if "; m2-bank-stable" in l:
            stable = True
            continue
        if "; ovl-pure" in l:
            pure = True
            continue
        if code(l) != "jp nes_dispatch_hl":
            continue
        j = i - 1
        while j >= 0 and not code(lines[j]):
            j -= 1
        m = LD_RE.match(code(lines[j]))
        if not m:
            continue
        t = int(m.group(1), 16)
        target = None
        if view is not None and stable and 0x8000 <= t < 0xC000:
            cand = f"nes_m2_b{view}_{t:04X}"
            if cand in labels:
                target = cand
                n_variant += 1
        if target is None and 0x6000 <= t < 0x8000 and f"nes_r_{t:04X}" in labels:
            # Translated PRG-RAM overlay block (it validates its own bytes);
            # a pure overlay source skips the re-validation.
            target = f"nes_r_{t:04X}"
            if pure and f"nes_r_{t:04X}_nc" in labels:
                target = f"nes_r_{t:04X}_nc"
            n_overlay += 1
        if target is None and t >= 0x8000 and f"nes_{t:04X}" in labels:
            target = f"nes_{t:04X}"
            if 0x8000 <= t < 0xC000:
                n_stub += 1
            else:
                n_fixed += 1
        if target is None:
            kept += 1
            continue
        out[j] = f"    ld a, BANK({target})\n    ld hl, {target}\n"
        out[i] = "    jp nes_jump_known_hl_a ; static banked-mapper edge\n"
    p.write_text("".join(out))
    print(f"banked-direct: {n_fixed} fixed, {n_variant} same-bank variant, {n_stub} stub, {n_overlay} overlay "
          f"static edge(s) made direct; {kept} kept on nes_dispatch_hl")


if __name__ == "__main__":
    main(sys.argv[1])
