#!/usr/bin/env python3
"""Generate runtime/interp.asm: a 6502 interpreter for code executing outside
PRG ROM (internal RAM $0000-$1FFF and cartridge PRG RAM $6000-$7FFF).

Static translation cannot see code that a game copies into RAM at runtime
(The Legend of Zelda runs its $6C90-$7EFF routines from PRG RAM). Dispatching
to a PC below $8000 enters this interpreter, which executes against exactly
the same canonical 6502 state (nes_a/x/y/sp, lazy C/Z/N shadows, nes_p) and
bus/flag helpers as translated code, and hands control back to translated
code through nes_dispatch_hl as soon as the PC returns to $8000-$FFFF.

Usage: python3 tools/gen_ram_interp.py > runtime/interp.asm
"""
import sys

OPS = {}
def op(code, mn, mode):
    OPS[code] = (mn, mode)

table = """
00 BRK imp|01 ORA izx|05 ORA zp|06 ASL zp|08 PHP imp|09 ORA imm|0A ASL acc|0D ORA abs|0E ASL abs
10 BPL rel|11 ORA izy|15 ORA zpx|16 ASL zpx|18 CLC imp|19 ORA aby|1D ORA abx|1E ASL abx
20 JSR abs|21 AND izx|24 BIT zp|25 AND zp|26 ROL zp|28 PLP imp|29 AND imm|2A ROL acc|2C BIT abs|2D AND abs|2E ROL abs
30 BMI rel|31 AND izy|35 AND zpx|36 ROL zpx|38 SEC imp|39 AND aby|3D AND abx|3E ROL abx
40 RTI imp|41 EOR izx|45 EOR zp|46 LSR zp|48 PHA imp|49 EOR imm|4A LSR acc|4C JMP abs|4D EOR abs|4E LSR abs
50 BVC rel|51 EOR izy|55 EOR zpx|56 LSR zpx|58 CLI imp|59 EOR aby|5D EOR abx|5E LSR abx
60 RTS imp|61 ADC izx|65 ADC zp|66 ROR zp|68 PLA imp|69 ADC imm|6A ROR acc|6C JMP ind|6D ADC abs|6E ROR abs
70 BVS rel|71 ADC izy|75 ADC zpx|76 ROR zpx|78 SEI imp|79 ADC aby|7D ADC abx|7E ROR abx
81 STA izx|84 STY zp|85 STA zp|86 STX zp|88 DEY imp|8A TXA imp|8C STY abs|8D STA abs|8E STX abs
90 BCC rel|91 STA izy|94 STY zpx|95 STA zpx|96 STX zpy|98 TYA imp|99 STA aby|9A TXS imp|9D STA abx
A0 LDY imm|A1 LDA izx|A2 LDX imm|A4 LDY zp|A5 LDA zp|A6 LDX zp|A8 TAY imp|A9 LDA imm|AA TAX imp|AC LDY abs|AD LDA abs|AE LDX abs
B0 BCS rel|B1 LDA izy|B4 LDY zpx|B5 LDA zpx|B6 LDX zpy|B8 CLV imp|B9 LDA aby|BA TSX imp|BC LDY abx|BD LDA abx|BE LDX aby
C0 CPY imm|C1 CMP izx|C4 CPY zp|C5 CMP zp|C6 DEC zp|C8 INY imp|C9 CMP imm|CA DEX imp|CC CPY abs|CD CMP abs|CE DEC abs
D0 BNE rel|D1 CMP izy|D5 CMP zpx|D6 DEC zpx|D8 CLD imp|D9 CMP aby|DD CMP abx|DE DEC abx
E0 CPX imm|E1 SBC izx|E4 CPX zp|E5 SBC zp|E6 INC zp|E8 INX imp|E9 SBC imm|EA NOP imp|EC CPX abs|ED SBC abs|EE INC abs
F0 BEQ rel|F1 SBC izy|F5 SBC zpx|F6 INC zpx|F8 SED imp|F9 SBC aby|FD SBC abx|FE INC abx
"""
for line in table.strip().splitlines():
    for ent in line.split("|"):
        c, mn, mode = ent.split()
        op(int(c, 16), mn, mode)
assert len(OPS) == 151

out = []
w = out.append

w("; Generated by tools/gen_ram_interp.py -- do not edit by hand.")
w("; 6502 interpreter for code executing from RAM ($0000-$1FFF, $6000-$7FFF).")
w("")
w('SECTION "NES RAM interpreter state", WRAM0')
w("nes_ipc_lo: ds 1 ; interpreted 6502 PC")
w("nes_ipc_hi: ds 1")
w("nes_iea_lo: ds 1 ; effective address of the current instruction")
w("nes_iea_hi: ds 1")
w("")
w('SECTION "NES RAM interpreter entry", ROM0')
w("; Input HL = NES PC below $8000. Enter the banked interpreter with the")
w("; helper bank recorded as the current code bank, so every bus/CHR helper")
w("; that temporarily switches ROMX banks returns to the interpreter.")
w("nes_interp_enter:")
w("    ld a, $FF")
w("    ld [nes_current_code_bank], a")
w("    ld [$2000], a")
w("    xor a")
w("    ld [$3000], a")
w("    jp nes_interp_run")
w("")
w('SECTION "NES RAM interpreter", ROMX, BANK[255]')
w("nes_interp_run:")
w("    ld a, l")
w("    ld [nes_ipc_lo], a")
w("    ld a, h")
w("    ld [nes_ipc_hi], a")
w("nes_interp_next:")
w("    ld a, [nes_ipc_hi]")
w("    cp $80")
w("    jr c, .fetch")
w("    ; Back in PRG ROM: continue in translated code.")
w("    ld h, a")
w("    ld a, [nes_ipc_lo]")
w("    ld l, a")
w("    jp nes_dispatch_hl")
w(".fetch:")
w("    call nes_interp_fetch")
w("    ld l, a")
w("    ld h, 0")
w("    add hl, hl")
w("    ld de, nes_interp_table")
w("    add hl, de")
w("    ld a, [hli]")
w("    ld h, [hl]")
w("    ld l, a")
w("    jp hl")
w("")
# helpers
w("; A = byte at PC, PC += 1. Clobbers HL (and whatever nes_cpu_read clobbers).")
w("nes_interp_fetch:")
w("    ld hl, nes_ipc_lo")
w("    ld a, [hli]")
w("    ld h, [hl]")
w("    ld l, a")
w("    inc hl")
w("    ld a, l")
w("    ld [nes_ipc_lo], a")
w("    ld a, h")
w("    ld [nes_ipc_hi], a")
w("    dec hl")
w("    ; fall through")
w("; A = NES bus byte at HL.")
w("nes_interp_read_hl:")
w("    ld a, h")
w("    cp $20")
w("    jp nc, nes_cpu_read")
w("    and $07")
w("    or $C0")
w("    ld h, a")
w("    ld a, [hl]")
w("    ret")
w("")
w("; Write A to NES bus address HL.")
w("nes_interp_write_hl:")
w("    ld e, a")
w("    ld a, h")
w("    cp $20")
w("    jr nc, .bus")
w("    and $07")
w("    or $C0")
w("    ld h, a")
w("    ld [hl], e")
w("    ret")
w(".bus:")
w("    ld a, e")
w("    jp nes_cpu_write")
w("")
w("; HL = 16-bit operand at PC, PC += 2.")
w("nes_interp_fetch16:")
w("    call nes_interp_fetch")
w("    push af")
w("    call nes_interp_fetch")
w("    ld h, a")
w("    pop af")
w("    ld l, a")
w("    ret")
w("")
w("; Effective-address calculators: leave EA in nes_iea and HL.")
w("nes_interp_ea_store:")
w("    ld a, l")
w("    ld [nes_iea_lo], a")
w("    ld a, h")
w("    ld [nes_iea_hi], a")
w("    ret")
w("nes_interp_ea_zp:")
w("    call nes_interp_fetch")
w("    ld l, a")
w("    ld h, 0")
w("    jr nes_interp_ea_store")
w("nes_interp_ea_zpx:")
w("    call nes_interp_fetch")
w("    ld l, a")
w("    ldh a, [nes_x]")
w("    add l")
w("    ld l, a")
w("    ld h, 0")
w("    jr nes_interp_ea_store")
w("nes_interp_ea_zpy:")
w("    call nes_interp_fetch")
w("    ld l, a")
w("    ldh a, [nes_y]")
w("    add l")
w("    ld l, a")
w("    ld h, 0")
w("    jr nes_interp_ea_store")
w("nes_interp_ea_abs:")
w("    call nes_interp_fetch16")
w("    jr nes_interp_ea_store")
w("nes_interp_ea_abx:")
w("    call nes_interp_fetch16")
w("    ldh a, [nes_x]")
w("    jr nes_interp_ea_add_a")
w("nes_interp_ea_aby:")
w("    call nes_interp_fetch16")
w("    ldh a, [nes_y]")
w("nes_interp_ea_add_a:")
w("    add l")
w("    ld l, a")
w("    jr nc, nes_interp_ea_store")
w("    inc h")
w("    jr nes_interp_ea_store")
w("; Pointer HL (zero page) -> 16-bit little-endian value with zero-page wrap.")
w("nes_interp_zp_ptr:")
w("    ld h, $C0")
w("    ld a, [hl]")
w("    inc l")
w("    ld h, [hl]")
w("    ld l, a")
w("    ld a, h")
w("    ld h, a")
w("    ret")
w("nes_interp_ea_izx:")
w("    call nes_interp_fetch")
w("    ld l, a")
w("    ldh a, [nes_x]")
w("    add l")
w("    ld l, a")
w("    call nes_interp_zp_ptr")
w("    jr nes_interp_ea_store")
w("nes_interp_ea_izy:")
w("    call nes_interp_fetch")
w("    ld l, a")
w("    call nes_interp_zp_ptr")
w("    ldh a, [nes_y]")
w("    jr nes_interp_ea_add_a")
w("")
w("; Load the current operand value into A (immediate or via EA).")
w("nes_interp_load_ea:")
w("    ld a, [nes_iea_lo]")
w("    ld l, a")
w("    ld a, [nes_iea_hi]")
w("    ld h, a")
w("    jp nes_interp_read_hl")
w("nes_interp_store_ea:")
w("    push af")
w("    ld a, [nes_iea_lo]")
w("    ld l, a")
w("    ld a, [nes_iea_hi]")
w("    ld h, a")
w("    pop af")
w("    jp nes_interp_write_hl")
w("")
w("; Taken control transfer to HL: poll for a pending NMI exactly like a")
w("; translated loop head, then continue at HL.")
w("nes_interp_goto_hl:")
w("    ld a, l")
w("    ld [nes_ipc_lo], a")
w("    ld a, h")
w("    ld [nes_ipc_hi], a")
w("    ldh a, [nes_host_vblank_pending]")
w("    and a")
w("    jp z, nes_interp_next")
w("    call nes_poll_nmi_hl")
w("    and a")
w("    jp nz, nes_nmi_entry")
w("    jp nes_interp_next")
w("")
w("nes_interp_illegal:")
w("    ld a, [nes_ipc_lo]")
w("    dec a")
w("    ldh [nes_fault_pc_lo], a")
w("    ld a, [nes_ipc_hi]")
w("    ldh [nes_fault_pc_hi], a")
w("    jp nes_unimplemented")
w("")

def operand_load(mode, lines):
    """Emit code that leaves the operand value in A."""
    if mode == "imm":
        lines.append("    call nes_interp_fetch")
    else:
        lines.append(f"    call nes_interp_ea_{mode}")
        lines.append("    call nes_interp_load_ea")

REG = {"A": "nes_a", "X": "nes_x", "Y": "nes_y"}
handlers = {}
for code, (mn, mode) in sorted(OPS.items()):
    L = []
    if mn in ("LDA", "LDX", "LDY"):
        operand_load(mode, L)
        L += [f"    ldh [{REG[mn[2]]}], a", "    ldh [nes_z_shadow], a", "    ldh [nes_n_shadow], a"]
    elif mn in ("STA", "STX", "STY"):
        L += [f"    call nes_interp_ea_{mode}", f"    ldh a, [{REG[mn[2]]}]", "    call nes_interp_store_ea"]
    elif mn in ("AND", "ORA", "EOR"):
        operand_load(mode, L)
        L += ["    ld e, a", "    ldh a, [nes_a]", {"AND": "    and e", "ORA": "    or e", "EOR": "    xor e"}[mn],
              "    ldh [nes_a], a", "    ldh [nes_z_shadow], a", "    ldh [nes_n_shadow], a"]
    elif mn in ("ADC", "SBC"):
        operand_load(mode, L)
        L += ["    ld e, a", "    ldh a, [nes_a]", f"    call nes_{mn.lower()}_a_e", "    ldh [nes_a], a"]
    elif mn in ("CMP", "CPX", "CPY"):
        operand_load(mode, L)
        reg = {"CMP": "nes_a", "CPX": "nes_x", "CPY": "nes_y"}[mn]
        L += ["    ld e, a", f"    ldh a, [{reg}]", "    call nes_compare_a_e"]
    elif mn == "BIT":
        operand_load(mode, L)
        L += ["    ld e, a", "    ldh a, [nes_a]", "    call nes_bit_a_e"]
    elif mn in ("ASL", "LSR", "ROL", "ROR"):
        helper = f"nes_{mn.lower()}_a"
        if mode == "acc":
            L += ["    ldh a, [nes_a]", f"    call {helper}", "    ldh [nes_a], a"]
        else:
            L += [f"    call nes_interp_ea_{mode}", "    call nes_interp_load_ea", f"    call {helper}", "    call nes_interp_store_ea"]
    elif mn in ("INC", "DEC"):
        L += [f"    call nes_interp_ea_{mode}", "    call nes_interp_load_ea",
              "    inc a" if mn == "INC" else "    dec a",
              "    ldh [nes_z_shadow], a", "    ldh [nes_n_shadow], a", "    call nes_interp_store_ea"]
    elif mn in ("INX", "INY", "DEX", "DEY"):
        r = REG[mn[2]]
        L += [f"    ldh a, [{r}]", "    inc a" if mn[0] == "I" else "    dec a", f"    ldh [{r}], a",
              "    ldh [nes_z_shadow], a", "    ldh [nes_n_shadow], a"]
    elif mn in ("TAX", "TAY", "TXA", "TYA"):
        s, d = REG[mn[1]], REG[mn[2]]
        L += [f"    ldh a, [{s}]", f"    ldh [{d}], a", "    ldh [nes_z_shadow], a", "    ldh [nes_n_shadow], a"]
    elif mn == "TSX":
        L += ["    ldh a, [nes_sp]", "    ldh [nes_x], a", "    ldh [nes_z_shadow], a", "    ldh [nes_n_shadow], a"]
    elif mn == "TXS":
        L += ["    ldh a, [nes_x]", "    ldh [nes_sp], a"]
    elif mn in ("CLC", "SEC"):
        L += ["    xor a" if mn == "CLC" else "    ld a, $01", "    ldh [nes_c_shadow], a"]
    elif mn in ("CLI", "SEI", "CLD", "SED", "CLV"):
        mask = {"CLI": 0x04, "SEI": 0x04, "CLD": 0x08, "SED": 0x08, "CLV": 0x40}[mn]
        L += ["    ldh a, [nes_p]", f"    or ${mask:02X}" if mn[0] == "S" else f"    and ${0xFF ^ mask:02X}", "    ldh [nes_p], a"]
    elif mn == "PHA":
        L += ["    ldh a, [nes_a]", "    call nes_stack_push_a"]
    elif mn == "PHP":
        L += ["    call nes_materialize_p", "    or $30", "    call nes_stack_push_a"]
    elif mn == "PLA":
        L += ["    call nes_stack_pop_a", "    ldh [nes_a], a", "    ldh [nes_z_shadow], a", "    ldh [nes_n_shadow], a"]
    elif mn == "PLP":
        L += ["    call nes_stack_pop_a", "    call nes_set_p_from_a"]
    elif mn == "NOP":
        pass
    elif mode == "rel":
        # Condition test leaves Z flag (host) meaning "not taken".
        cond = {
            "BPL": ["    ldh a, [nes_n_shadow]", "    bit 7, a", "    jr nz, .not_taken"],
            "BMI": ["    ldh a, [nes_n_shadow]", "    bit 7, a", "    jr z, .not_taken"],
            "BNE": ["    ldh a, [nes_z_shadow]", "    and a", "    jr z, .not_taken"],
            "BEQ": ["    ldh a, [nes_z_shadow]", "    and a", "    jr nz, .not_taken"],
            "BCC": ["    ldh a, [nes_c_shadow]", "    and a", "    jr nz, .not_taken"],
            "BCS": ["    ldh a, [nes_c_shadow]", "    and a", "    jr z, .not_taken"],
            "BVC": ["    ldh a, [nes_p]", "    and $40", "    jr nz, .not_taken"],
            "BVS": ["    ldh a, [nes_p]", "    and $40", "    jr z, .not_taken"],
        }[mn]
        L += ["    call nes_interp_fetch", "    ld e, a"] + cond + [
            "    ld a, [nes_ipc_lo]", "    ld l, a", "    ld a, [nes_ipc_hi]", "    ld h, a",
            "    ld a, e", "    ld d, $00", "    bit 7, a", "    jr z, :+", "    dec d", ":",
            "    add hl, de", "    jp nes_interp_goto_hl",
            ".not_taken:"]
    elif mn == "JMP" and mode == "abs":
        L += ["    call nes_interp_fetch16", "    jp nes_interp_goto_hl"]
    elif mn == "JMP" and mode == "ind":
        L += ["    call nes_interp_fetch16", "    call nes_jmp_indirect_hl", "    jp nes_interp_goto_hl"]
    elif mn == "JSR":
        L += ["    call nes_interp_fetch16", "    push hl",
              "    ld a, [nes_ipc_lo]", "    ld l, a", "    ld a, [nes_ipc_hi]", "    ld h, a", "    dec hl",
              "    call nes_stack_push_return_hl", "    pop hl", "    jp nes_interp_goto_hl"]
    elif mn == "RTS":
        L += ["    call nes_stack_pop_return_hl", "    inc hl", "    jp nes_interp_goto_hl"]
    elif mn == "RTI":
        L += ["    call nes_rti_pop_hl", "    jp nes_interp_goto_hl"]
    elif mn == "BRK":
        L += ["    ld a, [nes_ipc_lo]", "    ld l, a", "    ld a, [nes_ipc_hi]", "    ld h, a", "    inc hl",
              "    call nes_brk_hl", "    jp nes_irq_entry"]
    else:
        raise SystemExit(f"unhandled {mn} {mode}")
    handlers[code] = L

for code in sorted(handlers):
    mn, mode = OPS[code]
    w(f"nes_interp_op_{code:02X}: ; {mn} {mode}")
    out.extend(handlers[code])
    last = handlers[code][-1] if handlers[code] else ""
    if not last.startswith("    jp nes_") or last.startswith("    jp nes_interp_load") :
        w("    jp nes_interp_next")
    w("")

w("SECTION \"NES RAM interpreter table\", ROMX, BANK[255]")
w("nes_interp_table:")
for code in range(256):
    w(f"    dw nes_interp_op_{code:02X}" if code in OPS else "    dw nes_interp_illegal")
print("\n".join(out))
