use std::collections::{BTreeSet, VecDeque};
use std::fmt::Write;

use crate::{cfg::{ControlFlowGraph, EdgeKind}, ir, lr35902};

#[derive(Debug, Clone, Copy)]
pub struct EmitOptions {
    pub reset: u16,
    pub max_blocks: Option<usize>,
}

impl Default for EmitOptions {
    fn default() -> Self {
        Self { reset: 0x8000, max_blocks: Some(64) }
    }
}

fn terminal_mnemonic(m: crate::cpu6502::Mnemonic) -> bool {
    use crate::cpu6502::Mnemonic::*;
    matches!(m, Bcc|Bcs|Beq|Bmi|Bne|Bpl|Bvc|Bvs|Jmp|Jsr|Rts|Rti|Brk)
}

fn select_reachable(graph: &ControlFlowGraph, reset: u16, limit: usize) -> BTreeSet<u16> {
    let mut selected = BTreeSet::new();
    let mut queue = VecDeque::from([reset]);

    while let Some(addr) = queue.pop_front() {
        if selected.len() >= limit || !selected.insert(addr) {
            continue;
        }
        let Some(block) = graph.blocks.get(&addr) else { continue };

        for target in block.edges.iter().filter_map(|edge| edge.target) {
            if graph.blocks.contains_key(&target) && !selected.contains(&target) {
                queue.push_back(target);
            }
        }
    }

    selected
}

pub fn emit_cfg(graph: &ControlFlowGraph, options: EmitOptions) -> String {
    let mut out = String::new();
    writeln!(out, "; Generated by nes2gbc").unwrap();
    writeln!(out, "; Native LR35902 first-pass output").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "SECTION \"Generated NES entry\", ROM0").unwrap();
    writeln!(out, "nes_reset:").unwrap();
    writeln!(out, "    jp nes_{:04X}", options.reset).unwrap();
    writeln!(out).unwrap();

    let limit = options.max_blocks.unwrap_or(graph.blocks.len());
    let selected = select_reachable(graph, options.reset, limit);
    let mut external_targets = BTreeSet::new();

    for addr in &selected {
        let Some(block) = graph.blocks.get(addr) else { continue };
        writeln!(out, "nes_{:04X}:", block.start).unwrap();

        for instruction in &block.instructions {
            writeln!(
                out,
                "    ; ${:04X}: ${:02X} {:?} {:?}",
                instruction.pc,
                instruction.opcode,
                instruction.def.mnemonic,
                instruction.def.mode
            ).unwrap();

            match ir::lower_instruction(*instruction) {
                Ok(ops) => out.push_str(&lr35902::emit_ops(&ops)),
                Err(err) => { writeln!(out, "    ; TODO {err}").unwrap(); }
            }
        }

        if let Some(last) = block.instructions.last() {
            if !terminal_mnemonic(last.def.mnemonic) {
                if let Some(target) = block.edges.iter()
                    .find(|edge| matches!(edge.kind, EdgeKind::Fallthrough))
                    .and_then(|edge| edge.target)
                {
                    writeln!(out, "    jp nes_{target:04X}").unwrap();
                }
            }
        }

        for target in block.edges.iter().filter_map(|edge| edge.target) {
            if !selected.contains(&target) && graph.blocks.contains_key(&target) {
                external_targets.insert(target);
            }
        }
        writeln!(out).unwrap();
    }

    if !external_targets.is_empty() {
        writeln!(out, "; Targets outside this development slice trap here so the ROM still links.").unwrap();
        for target in external_targets {
            writeln!(out, "nes_{target:04X}:").unwrap();
            writeln!(out, "    jp nes_unimplemented").unwrap();
        }
        writeln!(out).unwrap();
    }

    writeln!(out, "nes_unimplemented:").unwrap();
    writeln!(out, "    di").unwrap();
    writeln!(out, ".hang:").unwrap();
    writeln!(out, "    halt").unwrap();
    writeln!(out, "    jr .hang").unwrap();

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cfg;

    #[test]
    fn emitted_program_starts_from_reset_not_address_order() {
        let mut prg = vec![0xEA; 0x8000];
        prg[0x0000] = 0x60; // $8000
        prg[0x1000] = 0x60; // $9000 reset target
        let graph = cfg::discover(0, &prg, &[0x8000, 0x9000]).unwrap();
        let asm = emit_cfg(&graph, EmitOptions { reset: 0x9000, max_blocks: Some(1) });
        assert!(asm.contains("jp nes_9000"));
        assert!(asm.contains("nes_9000:"));
    }

    #[test]
    fn omitted_target_gets_linkable_trap_stub() {
        let mut prg = vec![0xEA; 0x8000];
        prg[0x1000..0x1005].copy_from_slice(&[0xD0, 0x02, 0x60, 0xEA, 0x60]);
        let graph = cfg::discover(0, &prg, &[0x9000]).unwrap();
        let asm = emit_cfg(&graph, EmitOptions { reset: 0x9000, max_blocks: Some(1) });
        assert!(asm.contains("jp nes_unimplemented"));
    }
}
